"""251 exact method extraction. Original corpus is read-only."""
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / 'local-resources/regima/legacy-extraction/resources_by_swf/[172845].swf/scripts'
RECORDS = []


def take(relative, name):
    path = SRC / relative
    text = path.read_text(encoding='utf-8')
    match = re.search(r'(?:override\s+)?(?:public|protected|private)\s+(?:static\s+)?function\s+(?:get\s+)?' + re.escape(name) + r'\s*\(', text)
    assert match, (relative, name)
    start = match.start()
    brace = text.index('{', match.end())
    depth, end = 1, brace + 1
    while depth:
        depth += (text[end] == '{') - (text[end] == '}')
        end += 1
    method = text[start:end]
    RECORDS.append(dict(path=path.relative_to(ROOT).as_posix(), method=name,
        line=text[:start].count('\n') + 1,
        sourceSha256=hashlib.sha256(path.read_bytes()).hexdigest(),
        methodSha256=hashlib.sha256(method.encode()).hexdigest()))
    if relative == 'base/BasePet.as' and name == 'beMagicAttack':
        # Decompiled void returns in Boolean Bingo-only branches cannot compile.
        # restore_returnvoid restores the original two AVM2 instructions before execution.
        method = method.replace('return;', 'return false;')
        RECORDS[-1]['compileAdaptation'] = 'Temporary false returns for compiler only; original returnvoid restored in generated bytecode before execution.'
    return method


def methods(relative, names):
    # Deterministic inputs replace platform random/clock only; methods stay intact.
    return '\n'.join(take(relative, name) for name in names).replace('Math.random()', 'Config.random()').replace('getTimer()', 'Config.now')
