"""Finite family acceptance inventory, declared independently of trace outputs."""
CONTRACTS = [
 ('entry.forms','base/BaseHero.as','addPetByPi','init-','PetCombatRuntime','四类直接继承BasePet；按petName实例化对应类'),
 ('ai.priority','base/BasePet.as','myIntelligence','priority-','PetCombatRuntime','sld→txlj→sybh→xwaoyi→秒拍普攻；AI后CD减一'),
 ('ai.range','base/BasePet.as','myIntelligence','outside-|inside-','PetCombatTargeting','40/120/150/150内才按0.7首随机普攻，失败再独立0.3随机'),
 ('ai.owner','base/BasePet.as','myIntelligence','remote-','HeroPartyRuntimeBridge','single或sourceRole.sid本地才自动选择；两玩家各自owner'),
 ('ai.target','base/BasePet.as','searchTarget','outside-','PetCombatTargeting','原数组首个距离<=1200目标；不是最近排序；>=1200或死亡清目标'),
 ('ai.follow','base/BasePet.as','followSource','outside-','PetCombatEntitySession','跟随阈值640；追击只按x转向；warp与地面规则复用205/217证据'),
 ('normal.1','export/pet/PetTurtle1.as','normalHit','normal-','PetCombatRuntime','真普攻hit1；第三cell countdown10创建PetTurtle1Bullet1'),
 ('normal.2','export/pet/PetTurtle2.as','normalHit','normal-','PetCombatRuntime','真普攻hit1；第四cell countdown10创建PetTurtle2Bullet1'),
 ('normal.3','export/pet/PetTurtle3.as','normalHit','normal-','PetCombatRuntime','真普攻hit1；第四cell countdown10创建PetTurtle2Bullet1'),
 ('normal.4','export/pet/PetTurtle4.as','normalHit','normal-','PetCombatRuntime','真普攻hit1；第四cell countdown10创建PetTurtle2Bullet1'),
 ('sld.gates','export/pet/PetTurtle1.as','beforeSkill1Start','gate-|low-mp-','PetTurtleSkillSystem','已学、20MP、距离50..200含边界'),
 ('sld.release','export/pet/PetTurtle1.as','releSkill1','release-','PetCombatRuntime','新attack id、保护10tick、hit2、扣20MP'),
 ('sld.effect','export/pet/PetTurtle1.as','doHit2','frame-','PetProjectileCombatSystem','FollowBaseObjectBullet；hurt不断；创建即cureHp(uint(noncritPower))，不是命中治疗'),
 ('sld.link-heal','export/pet/PetTurtle2.as','doHit2','frame-','PetBattleOwnershipSystem','双方buff存在才直接写hero HP；四阶SetHHp事件；不递归hero cureHp'),
 ('txlj.release','export/pet/PetTurtle2.as','releSkill2','release-','PetBattleOwnershipSystem','无动作切换；双方同buff；first/second转uint；仅harm存在扣20MP'),
 ('txlj.damage','base/BaseHero.as','reduceHp','settlement','HeroCombatSystem','盾优先；双buff时pet ceil(5%)，hero int(95%)后ceil；显示不是HP差'),
 ('txlj.heal','base/BaseHero.as','cureHp','settlement','PetBattleOwnershipSystem','双buff时pet和hero均int(105%)，hero后ceil不恢复小数'),
 ('sybh.release','export/pet/PetTurtle3.as','releSkill3','release-','PetCombatRuntime','20MP/hit3/保护10；第三cell countdown10出效果'),
 ('sybh.effects','export/pet/PetTurtle4.as','doHit3','frame-','PetProjectileCombatSystem','三阶scale1，四阶scale2；四阶hit3间隔frameClips*.25'),
 ('aoyi.gate','export/pet/PetTurtle4.as','beforeSkill4Start','aoyi-','PetCombatRuntime','目标、已学、MP>=30；releSkill4不扣蓝'),
 ('aoyi.chain','export/pet/PetTurtle4.as','releSkill4','aoyi-','PetCombatRuntime','8种已学组合；立即/2秒/4秒免费SLD、免费TXLJ、SYBH持续5秒'),
 ('aoyi.damage-window','export/pet/PetTurtle4.as','doHit3InAoyi','aoyi-','PetProjectileCombatSystem','不随末帧销毁；120ticks@24；static世界根；末帧仍可碰撞'),
 ('aoyi.hurt','export/pet/PetTurtle4.as','reduceHp','aoyi-hurt-','PetCombatEntitySession','仍扣HP；压制hurt参数/反击；GXP或奥义拒绝击退；hurt动作清isAoyi'),
 ('aoyi.cleanup','export/pet/PetTurtle4.as','releSkill4','aoyi-rest|aoyi-dead|aoyi-destroy-','PetCombatRuntime','延迟回调只检petInfo/isFight/!dead；活宠销毁后回调1009是源缺陷'),
 ('damage.power','petInfo/PetInfo.as','getPetHarmObj','power-|init-','PetProjectileCombatSystem','first总乘1.05；四阶才乘魔花；暴击独立；fsnl uint'),
 ('damage.snapshot','base/BaseBullet.as','refreshSourceRoleAttackInfoObject','hit','PetProjectileCombatSystem','setAction缓存伤害；pet atk*2.8；成功命中后再刷新供下一个目标'),
 ('damage.dedup','base/BaseBullet.as','checkAttack','hit','PetProjectileCombatSystem','每攻击id目标去重；interval相等时换id；miss行为由怪物决定'),
 ('damage.defense','base/BaseMonster.as','getRealHurt','hit','PetProjectileCombatSystem','物理atk/def比例、魔法mDef比例；上限1.1、负比例1、int返回'),
 ('hurt.counter','base/BasePet.as','reduceHp','counter-|hurt-','PetCombatEntitySession','宠物本身非致死param2=true才QLFJ随机反击；不是主人任意受击触发'),
 ('hurt.death','base/BasePet.as','reduceHp','dead-','PetCombatEntitySession','single首次dead扣寿命一次，死亡动画结束destroy；原伤害显示可大于HP差'),
 ('lifecycle.destroy','base/BasePet.as','destroy','destroy-','PetCombatRuntime','销毁body/buff/bullet，清sourceRole宠物和owner；现代需取消所有自身回调'),
 ('lifecycle.replace','base/BaseHero.as','changePet','destroy-','HeroPartyRuntimeBridge','changePet先destroy旧宠再initPet；重试/返回经hero销毁链'),
]

